name: Build_FritzBox_7490

on:
  workflow_dispatch:

concurrency:
  group: build-7490
  cancel-in-progress: true
  queue: single

jobs:
  build:
    permissions:
      packages: read
      contents: write
    runs-on: ubuntu-24.04
    if: github.repository != 'freetz-ng/freetz-ng' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: System vorbereiten und Compiler installieren
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install \
            locales pv cpio rsync kmod imagemagick inkscape graphicsmagick subversion git bc unar wget sudo gcc g++ binutils autoconf automake \
            autopoint libtool-bin make bzip2 libreadline-dev zlib1g-dev flex bison patch texinfo gettext pkg-config ecj \
            perl libstring-crc32-perl ruby gawk libusb-dev unzip intltool libacl1-dev libcap-dev libc6-dev-i386 \
            libelf-dev libncurses-dev gcc-multilib bsdmainutils lib32stdc++6 libglib2.0-dev ccache cmake lib32z1-dev libsqlite3-dev sqlite3 libzstd-dev \
            netcat-openbsd curl uuid-dev libssl-dev libgnutls28-dev u-boot-tools device-tree-compiler

      - name: Spracheinstellungen einrichten
        run: |
          sudo locale-gen en_US.utf8 && sudo locale-gen de_DE.UTF-8
          sudo update-locale LANG=de_DE.UTF-8

      - name: Eigene .config einspielen
        run: |
          make dirclean
          mkdir -p images
          cat << 'EOF' > .config
FREETZ_CONFIG_OVERRIDE=y
FREETZ_TYPE_7490=y
FREETZ_TYPE_LANG_DE=y
FREETZ_AVM_VERSION_07_6X=y
FREETZ_AVM_VERSION_STRING="07.62"
FREETZ_SHOW_EXPERT=y
FREETZ_IPV6=y
FREETZ_MODULE_ip6table_nat=y
FREETZ_MODULE_ip6t_MASQUERADE=y
FREETZ_MODULE_ip6table_mangle=y
FREETZ_MODULE_ip6t_HL=y
FREETZ_MODULE_nf_conntrack_ipv6=y
FREETZ_PACKAGE_MOD_CGI=y
FREETZ_PACKAGE_NDPPD=y
FREETZ_PATCH_COCKPIT_UNSECURE=y
FREETZ_MODIFY_DSL_SETTINGS=y
EOF
          yes "" | make oldconfig

      - name: Firmware kompilieren
        run: |
          make

      - name: Variablen vorbereiten
        id: vars
        run: |
          LAST_FILE="$(ls images/*.image | head -n 1 | xargs basename)"
          NAME_FILE="$(echo "$LAST_FILE" | sed 's,_[0-9]*,,;s,\.image,,')"
          echo "last=${LAST_FILE}" >> $GITHUB_OUTPUT
          echo "name=${NAME_FILE}" >> $GITHUB_OUTPUT
          test -n "${NAME_FILE}"

      - name: Firmware als Release hochladen
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.vars.outputs.name }}
          name: ${{ steps.vars.outputs.name }}
          body: |
            Build fuer FRITZ!Box 7490 erfolgreich abgeschlossen.
            Die fertige Datei befindet sich im Anhang.
          prerelease: false
          allowUpdates: true
          artifacts: "images/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
